import type { Metadata } from "next";
import { Geist, Geist_Mono, Pinyon_Script, Great_Vibes, Parisienne, Allura, Tangerine } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pinyonScript = Pinyon_Script({
  weight: "400",
  variable: "--font-pinyon",
  subsets: ["latin"],
});

const greatVibes = Great_Vibes({
  weight: "400",
  variable: "--font-great-vibes",
  subsets: ["latin"],
});

const parisienne = Parisienne({
  weight: "400",
  variable: "--font-parisienne",
  subsets: ["latin"],
});

const allura = Allura({
  weight: "400",
  variable: "--font-allura",
  subsets: ["latin"],
});

const tangerine = Tangerine({
  weight: "700",
  variable: "--font-tangerine",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "JUICE5 - nuit info 2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pinyonScript.variable} ${greatVibes.variable} ${parisienne.variable} ${allura.variable} ${tangerine.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
